from typing import Any, Iterator

class Sequence:
    def __init__(self, *args, **kwargs) -> None:
        ...

    def build(self, x) -> None:
        ...

    def iter_seq(self) -> Iterator:
        ...

    def get_at(self, i: int) -> Any:
        ...

    def set_at(self, i: int, x: Any) -> None:
        ...

    def insert_at(self, i: int, x: Any) -> None:
        ...

    def delete_at(self, i: int) -> None:
        ...

    def insert_first(self, x: Any) -> None:
        ...

    def delete_first(self) -> None:
        ...

    def insert_last(self, x: Any) -> None:
        ...

    def delete_last(self) -> None:
        ...